### ISSUE TITLE
Request: Need to be able to change marker shape as well as color on the Taylor diagrams

### ISSUE THREAD

**Issue by mariellep** [PeterRochford/SkillMetrics#19] opened 2020-03-18 04:31 UTC
Thank you for this tool! However, I'm running into a particularly annoying issue:

I need to be able to have specifically colored points for each particular model I'm comparing to the reference. I've solved this particular issue by using the "overlay" option and plotting each single model individually on the plot with the color tuple as the markerColor specification. Here's an example: 

![DJF_NP_ua_taylorplot](https://user-images.githubusercontent.com/3780369/76924918-192cbe80-6895-11ea-9ff4-d64021128e8f.png)

HOWEVER. Now I need to have different marker shapes as well as marker colors! Ideally, there would be a markerShape flag that would allow you to specify markerShape="x" vs markerShape="." etc. as well as defining markerColor="blue" or whatever. I had hoped that the using the existing markerLegend option would be sufficient, but for some reason it doesn't like my pre-defined color tuples in combination with this option. 

For reference, here's my existing code:

            #Initialize the plot
            ts=sm.taylor_statistics(store_mod[d],rean_ref)
            mod_col=rgb_order[0]

            ref_sd[0]=ts['sdev'][0]
            ref_sd[1]=ts['sdev'][1]

            ref_rm[0]=ts['crmsd'][0]
            ref_rm[1]=ts['crmsd'][1]

            ref_cc[0]=ts['ccoef'][0]
            ref_cc[1]=ts['ccoef'][1]

            sm.taylor_diagram(ref_sd,ref_rm,ref_cc,styleOBS='-.',widthOBS=3,markerlabel=['REAN',d],
                             markerSize=30,tickRMS = tr,axismax=am,markerColor=mod_col) 

            i=1
           #Add the other points
            for d in comb_list[1:]:
                
                ts=sm.taylor_statistics(store_mod[d],rean_ref)
                mod_col=rgb_order[i]
                ref_sd[0]=ts['sdev'][0]
                ref_sd[1]=ts['sdev'][1]
                ref_rm[0]=ts['crmsd'][0]
                ref_rm[1]=ts['crmsd'][1]
                ref_cc[0]=ts['ccoef'][0]
                ref_cc[1]=ts['ccoef'][1]
                sm.taylor_diagram(ref_sd,ref_rm,ref_cc,styleOBS='-.',widthOBS=3,markerlabel=['REAN',d],
                                 markerSize=30,markerColor=mod_col,overlay='on')    
                i+=1

**Comment by juan-guerschman** [comment] 2020-06-23 23:49
I run into the same issue. Would love to be able to have more and easier control over marker color, type, size, etc. 
![image](https://user-images.githubusercontent.com/8801702/85478564-d438c680-b5ff-11ea-9ecf-fbc133bd299f.png)

Looks like the default behaviour is to go through some markers in blue, then change to red, green, etc. I want to be able to choose my own.

**Comment by juan-guerschman** [comment] 2020-06-24 00:10
here's where marker and colors are decided by default:
https://github.com/PeterRochford/SkillMetrics/blob/master/skill_metrics/plot_pattern_diagram_markers.py#L55

would be great to have the option of passing a list with marker styles, colors and sizes which could overwrite this default. My Python skills are limited but I may give it a try.

**Comment by hhh-1996** [comment] 2020-06-30 10:51
> here's where marker and colors are decided by default:
> https://github.com/PeterRochford/SkillMetrics/blob/master/skill_metrics/plot_pattern_diagram_markers.py#L55
> 
> would be great to have the option of passing a list with marker styles, colors and sizes which could overwrite this default. My Python skills are limited but I may give it a try.

Hello, have you solved your problem?
There is an error in my new  Marker and Markercolor which I defined.

**Comment by juan-guerschman** [comment] 2020-06-30 11:04
> Hello, have you solved your problem?
> There is an error in my new Marker and Markercolor which I defined.

No. the problem is in https://github.com/PeterRochford/SkillMetrics/blob/master/skill_metrics/plot_pattern_diagram_markers.py#L62
if less than 11 points, it will take the color but ignore the symbols passed.

If 11 or more symbols, it will ignore both and use the default symbols and colors. 
I haven't fixed it.

**Comment by Caroline19941** [comment] 2020-07-16 13:56
I have had the same problem and solved it for my use. I do not think that it is a wonderful solution, and I also may have overlooked some burdens that come if you use it differently than myself, but here is how I use it now:

I define a marker dictionary, that looks e.g. like:
`marD = {'*': {'w': ['darkorange', 'darkgoldenrod', 'cadetblue']}, 'p': {'w': ['darkorange', 'darkgreen'], 'k': ['darkorange', 'darkgreen']}, 'h': {'w': ['darkorange', 'darkgreen']}, 's': {'w': ['darkorange', 'darkgreen'], 'k': ['darkorange', 'darkgreen']}, 'd': {'w': ['darkorange', 'darkgreen'], 'k': ['darkorange', 'darkgreen']}, '^': {'w': ['darkorange', 'darkgreen'], 'k': ['darkorange', 'darkgreen']}, 'v': {'w': ['darkorange', 'darkgreen'], 'k': ['darkorange', 'darkgreen']}}`

First, the markershape is defined (e.g. '*'), then, the edgecolor is defined (e.g. 'w') and then, the facecolor (e.g. 'darkorange').

taylor_label is in my case just the list that defines the legend for the edgecolors, because I already have a legend for the facecolors and the markerstyles, but you can change that (actually, I commented this part because I used to use it earlier, so you basically need to uncomment it (lines 158-1874 in plot_pattern_diagram.py, and do not deifine the edgecolors in the marker dictionary, e.g. marD = {'*': ['darkorange', 'darkgoldenrod', 'cadetblue']}). comment instead lines 110-156.

With the edited code, the following command
`    sm.taylor_diagram(sdev,crmsd,ccoef, checkStats='on', styleOBS = '-', markerLabel = taylor_label,
                    colOBS = 'r', markerobs = 'o', markerLegend = 'off',stylerms ='-',colRMS='grey',
                    titleOBS = 'Observation', titleRMS = 'off', titleRMSDangle=20, colCOR='dimgrey', 
                    MarkerDictCH=marD, alpha=0.7, markerSize= 9) 
`
gives me this result:
![Taylor_diagram_edited](https://user-images.githubusercontent.com/56937273/87677991-b122b200-c77a-11ea-8121-e78b17d44699.png)

I basically added the option `MarkerDictCH`, changed lines in 'plot_pattern_diagram_markers' and 'add_legend'.

Now I am not sure how I can share my code, should I upload it on my github? I don't think this is the way to go.

So let's copy the most important lines from 'plot_pattern_diagram_markers' here:

`    # edit 2020-05-27 CH
    # use markerLegend = 'off',
    # but give markerlabels
    # ch for caroline haslebacher
    # changes right below
    elif option['markerdictch'] != None:
        # markerlabels for legend. plot markers
        markerlabel = []

        # create list from dict
        colmar = [] # colmar for color (belonging to a marker)
        markcol = [] # markcol for marker (belonging to a climate model)
        edgecol = [] # edgecolors for forcings
        hp = () # for handles

        for idx1, mar in enumerate(option['markerdictch'].keys()):

            for forcing in option['markerdictch'][mar].keys():
                for idx2, col in enumerate(option['markerdictch'][mar][forcing]):
                    # print(col)
                    colmar.append(col)
                    markcol.append(mar)
                    if forcing == 'w':
                        edgecol.append(col) # do not use white edgecolor. Just use same color as markercolor
                    else:
                        edgecol.append(forcing)

                    # this is for legend
                    # idx2 == 0 is there so that we take only one color

                    # case where we have only model data, no ERA5 data (ERA5 is reference)
                    if idx1 == 0 and idx2 == 0 and mar != '*': 
                        if forcing == 'w': # do not use white edgecolor
                            my_edge_col = col
                        else:
                            my_edge_col = forcing
                        mark = mlines.Line2D([], [], color=col, marker=mar, markeredgecolor = my_edge_col,
                                    markersize=markerSize)
                        hp += tuple([mark])
                        rgba = clr.to_rgb('k') + (alpha,) # not really needed, but otherwise rgba is not defined for add_legend
                                        
                    # case where we have ERA5 data
                    # make sure that we only run this code if ERA5 is NOT the reference, so if the marker of ERA5 ('*') is in the markerdict
                    if '*' in option['markerdictch'].keys():
                        if idx1 == 1 and idx2 == 0: # take second entry for displaying forcing, since ERA5 is reanalysis and has no different forcings
                            # markerlabel.append(option['markerlabel'][i]) # only plot legend of markers, which indicate climate model
                            if forcing == 'w': # do not use white edgecolor
                                my_edge_col = col
                            else:
                                my_edge_col = forcing
                            mark = mlines.Line2D([], [], color=col, marker=mar, markeredgecolor = my_edge_col,
                                        markersize=markerSize)
                            hp += tuple([mark])
                            rgba = clr.to_rgb('k') + (alpha,) # not really needed, but otherwise rgba is not defined for add_legend
                    
        # # markerlabels for legend. plot markers
        # markerlabel = []

        # # create list from dict
        # colmar = [] # colmar for color (belonging to a marker)
        # markcol = [] # markcol for marker (belonging to a climate model)
        # hp = () # for handles
        # for mar in option['markerdictch'].keys():
        #     # markerlabel.append(option['markerlabel'][i]) # only plot legend of markers, which indicate climate model
        #     mark = mlines.Line2D([], [], color='k', marker=mar, # edgecolor
        #                   markersize=markerSize)
        #     hp += tuple([mark])
        #     rgba = clr.to_rgb('k') + (alpha,) # not really needed, but otherwise rgba is not defined for add_legend

        #     for col in option['markerdictch'][mar]:
        #         colmar.append(col)
        #         markcol.append(mar)

        
        
            # print(f'len of X: {len(X)}, len of Y: {len(Y)}, len of colmar: {len(colmar)}, len of markcol: {len(markcol)}, len of edgecol: {len(edgecol)}')
        
        # Add legend for forcings
        # only useful if not only ERA5 data is in it
        if len(hp) != 0:
            if len(option['markerlabel']) == 0:
                warnings.warn('No markers within axis limit ranges.')
            else:
                
                for h in hp: h.set_linestyle("") # Caroline: do not display lines
                add_legend(option['markerlabel'], option, rgba, markerSize, fontSize, hp)
            
`

**Comment by dabeljmu** [comment] 2021-08-20 21:34
Hey Caroline,

I really like your code and it is doing exactly what I need for my plot as well. I copied your lines into 'plot_pattern_diagram_markers' but when I execute my script with the additional option 'markerdictch' it gives me the following error:

ValueError: Unrecognized option: markerdictch

which occurs in 'get_taylor_diagram_options'

Is there anything else to change or have I just missed something?

Kind regards,
Daniel

**Comment by CarolineHaslebacher** [comment] 2021-08-22 09:28
@dabeljmu  
Hi Daniel, 
Nice that you can use my changes! Thank you for trying it out and giving me feedback.
Yes, you need to define the `MarkerDictCH` as an option. If you already did that and the error persists, a simple python kernel restart should do the trick.
If you did not define it as an option in `get_taylor_diagram_options.py`, then you should add the following lines in `get_taylor_diagram_options.py`:
```
    # define it in the docs (optional)
    # option['markerdictch']    : (CH, 2020-05-27), define dictionary for marker and color 
    #                             (e.g. {'marker1': ['color1', 'color2',..], 'marker2': ['color2',...]})
    #                            I use it for displaying same pressure levels for different climate models
    #                            default: None
    # option['legendch']        : (CH, 2020-08-11), choose if legend is plotted

    # set as an option, define default values (put these lines at the start somewhere after '# Set default parameters for all options'

    option['markerdictch'] = None # Caroline Haslebacher created this
    option['legendch'] = True # Caroline Haslebacher, 2020-08-11


    # then, after "# Check values for specific options", allow for user input:
            elif optname == 'markerdictch': # CH introduced this on 2020-05-27
                option['markerdictch'] = optvalue

            elif optname == 'legendch': # CH introduced this on 2020-08-11s
                option['legendch'] = optvalue
```

I did not show the changes I made to `add_legend.py`. I will just copy the whole edited script below:
```
import math
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import warnings

def add_legend(markerLabel, option, rgba, markerSize, fontSize, hp = []):
    '''
    Adds a legend to a pattern diagram.
    
    Adds a legend to a plot according to the data type containing the 
    provided labels. If labels are provided as a list they will appear 
    in the legend beside the marker provided in the list of handles in  
    a one-to-one match. If labels are provided as a dictionary they will 
    appear beside a dot with the color value given to the label.
    
    INPUTS:
    markerLabel : list or dict variable containing markers and labels to
                  appear in legend
                  
                  A list variable must have the format:
                  markerLabel = ['M1', 'M2', 'M3']
                  
                  A dictionary variable must have the format:
                  markerLabel = = {'ERA-5': 'r', 'TRMM': 'b'}
                  where each key is the label and each value the color for 
                  the marker
    
    hp : list of plot handles that match markerLabel when latter is a list
    option : dictionary containing option values. (Refer to 
        GET_TARGET_DIAGRAM_OPTIONS function for more information.)
    option['numberpanels'] : Number of panels to display
                             = 1 for positive correlations
                             = 2 for positive and negative correlations
    rgba : a 4-tuple where the respective tuple components represent red, 
           green, blue, and alpha (opacity) values for a color
    markerSize : point size of markers
    fontSize : font size in points of labels
    
    OUTPUTS: 
    None

    Created on Mar 2, 2019
    Revised on Mar 2, 2019
    
    Author: Peter A. Rochford
        Symplectic, LLC
        www.thesymplectic.com
        prochford@thesymplectic.com
    '''

    if type(markerLabel) is list:
        print('is list')
        # Check for empty list of plot handles

        # changed by CH on 2020-05-27
        if len(hp) == 0:
            # raise ValueError('Empty list of plot handles') 
            if len(markerLabel) <= 8: # caroline changed limit value from 6 to 8
                # Put legend in a default location
                markerlabel = tuple(markerLabel)
                plt.legend(hp, markerlabel,marker=mar, loc = 'lower left', markerfacecolor = 'k', 
                                    fontsize = fontSize, numpoints=1,
                                    bbox_to_anchor=(0.2,-0.3))
                
            else:
                # Put legend to right of the plot in multiple columns as needed

                nmarkers = len(markerLabel)
                ncol = int(math.ceil(nmarkers / 15.0))
                markerlabel = tuple(markerLabel)

                # Shift figure to include legend
                plt.gcf().subplots_adjust(right=0.6)

                # Plot legend of multi-column markers
                # Note: do not use bbox_to_anchor as this cuts off the legend
                plt.legend(hp, markerlabel, marker=mar, loc = (0,-0.2), markerfacecolor = 'k', 
                            fontsize = fontSize, numpoints=1, ncol = ncol)

        elif len(hp) != len(markerLabel):
            raise ValueError('Number of labels and plot handle do not match: ' +
                             str(len(markerLabel)) + ' != ' + str(len(hp)))
        
        # Add legend using labels provided as list
        if len(markerLabel) <= 8: # caroline changed limit value from 6 to 8
            # Put legend in a default location
            markerlabel = tuple(markerLabel)
            plt.legend(hp, markerlabel, loc = 'upper left',
                                 fontsize = fontSize, numpoints=1,
                                 bbox_to_anchor=(-0.1 ,-0.3)) # (1.2,1.0)
            print('yes, this is here')
        else:
            # Put legend to right of the plot in multiple columns as needed

            nmarkers = len(markerLabel)
            ncol = int(math.ceil(nmarkers / 15.0))
            markerlabel = tuple(markerLabel)

            # Shift figure to include legend
            plt.gcf().subplots_adjust(right=0.6)

            # Plot legend of multi-column markers
            # Note: do not use bbox_to_anchor as this cuts off the legend
            plt.legend(hp, markerlabel, loc = (1.1, 0.25),
                        fontsize = fontSize, numpoints=1, ncol = ncol)

    elif type(markerLabel) is dict:
        
        # Add legend using labels provided as dictionary
            
        # Define legend elements
        legend_elements = []
        for key, value in markerLabel.items():
            legend_object = Line2D([0], [0], marker='.', markersize = markerSize,
                 markerfacecolor = rgba, markeredgecolor = value, label=key, linestyle='')
            legend_elements.append(legend_object)

        # Put legend in a default location
        plt.legend(handles=legend_elements, loc = 'lower left', # Caroline on 24.06.2020;  loc = 'upper right',
                             fontsize = fontSize, numpoints=1,
                             bbox_to_anchor=(0,-0.2))
                             
        if _checkKey(option, 'numberpanels') and option['numberpanels'] == 2:
            # add padding so legend is not cut off
            plt.tight_layout(pad=1)
    else:
        raise Exception('markerLabel type is not a list or dictionary: ' + 
                        str(type(markerLabel)))
    
def _checkKey(dictionary, key): 
    if key in dictionary.keys(): 
        return True
    else: 
        return False 
```

Please let me know if you still get the same error!

**Comment by dabeljmu** [comment] 2021-08-23 16:42
Hi Caroline,

thanks a lot for your quick and very helpful answer. With this, the changed code is running and the error is solved.

However, I am a bit confused about two things - which definitely causes in my limited python-skills...

1) The format of the input data. I'm providing the data as a np.array which worked quite fine for me and which works fine as well if I only have one marker (cp. code l 23). However, if I want to give a second marker with the first two points as '*' and the second two as 'p' I get an error in 'add_legend.py' (l 82):
str(len(markerLabel)) + ' != ' + str(len(hp)))
ValueError: Number of labels and plot handle do not match: 4 != 1

Thus, I'm wondering about the structure and format of your input data.

2) Changing the marker. If I want to change the marker in the working code form '*' to any other I get the following error in 'plot_pattern_diagram_markers.py' (l 134):
hp += tuple([mark])
UnboundLocalError: local variable 'mark' referenced before assignment

Since I don't want to work with if-statements - which would be the googled solution - , I don't know how to fix this and change the marker.

I know, the answers are at least partially quite python-basics but maybe you can provide an idea for the solution.

Greetings

> import numpy as np
> import matplotlib.pyplot as plt
> import skill_metrics as sm
>  
> sdev = np.zeros((5))
> crmsd = np.zeros((5))
> ccoef = np.zeros((5))
> 
> sdev[:] = [1, 1.1, 1.2, 0.9, 0.7]
> crmsd[:] = [0, 1.8, 2, 1.2, 0.5]
> ccoef[:] = [1, 0.7, 0.8, 0.8, 0.75]
> 
> label = ['obs','01','02','03','04']
> 
> marD = {'*': {'w': ['darkorange', 'darkgoldenrod', 'darkgreen', 'skyblue']}#           ,'p': {'w': ['darkorange', 'darkgoldenrod', 'darkgreen', 'skyblue']}
>         }
> 
> fig, ax = plt.subplots(1,1)
> sm.taylor_diagram(sdev,crmsd,ccoef, checkStats='on', styleOBS = '-', 
>                   markerLabel = label, colOBS = 'r', markerobs = 'o', 
>                   markerLegend = 'off',stylerms ='-',colRMS='grey', titleOBS = 'Obs', 
>                   titleRMS = 'off', titleRMSDangle=20, colCOR='dimgrey', MarkerDictCH=marD, 
>                   alpha=0.7, markerSize= 9)
> 
> plt.tight_layout()
> plt.savefig('taylor_tester.png' ,dpi=300, bbox_inches='tight')
> plt.show()
> exit()
>

**Comment by CarolineHaslebacher** [comment] 2021-08-23 20:10
@dabeljmu 
Hi Daniel,
Glad you are a step further!
I have to say that I really customized the function for my needs and hardcoded a lot of my needs (which is kind of bad practice, we now see why), so it might not do exactly what you need.
Anyway, I've tried out your code and catched a few things, but first let me answer your questions:
1. numpy arrays as input are just fine and should not be causing your error. The error is rather caused by my implementation of the marD input! The labels which you provide through `label` are not going to name the individual data points, but rather the facecolors ('w' for 'white' and 'k' for 'black'), in my case 'hist' and 'present'. I did this since I've already had a separate code generating a legend for the colors. If needed, you could implement that the legend works for your individual points!
The code expects you to input the same amount of categories as you provide facecolors. However, I've hardcoded a special case whenever I use the marker '*', so I recommend you to just not use it or go through the code and edit, or ask again.

2. I wasn't able to reproduce your second error. However, in the following, I provide a minimal working example and hope it solves your issues:

Additionally, I got an error warning me that your 'made-up' data is not consistent with the equation RMSs(i) = sqrt(STDs(i).^2 + STDs(1)^2 - 2*STDs(i)*STDs(1).*CORs(i)) (see `taylor_diagram.py`, documentation (l. 39))


```
import numpy as np
import matplotlib.pyplot as plt
import skill_metrics as sm

# I define consistent 'fake-data'
# also note that the first entry should not show up in the marD because it is the reference
sdev = [1.,         0.79489189, 0.72909418, 0.67983078, 0.66597742, 0.81855761, 0.234, 0.564, 0.675]
crmsd = [0.49512275, 0.35768422, 0.4479255,  0.54590334, 0.56531812, 0.49595067, 0.7731455, 0.595637, 0.4708768]
ccoef = [1.,         0.94598721, 0.91273604, 0.85621265, 0.84382842, 0.86986516, 0.9765, 0.854, 0.914]

# put the fake-data into arrays
sdev = np.array(sdev)
crmsd = np.array(crmsd)
ccoef = np.array(ccoef)

# define the marker-dict 'marD'
# 'w' and 'k' define the facecolors which I used to distinguish different categories belonging to the same object
marD = {'*': {'w': ['darkorange', 'darkgoldenrod'], 'k': ['darkgoldenrod', 'cadetblue']}, 'p': {'w': ['darkorange', 'darkgreen'], 'k': ['darkorange', 'red']}}

# provide labels for the facecolor categories (in this case, we need two labels)
taylor_label = ['hist', 'present']

# call taylor_diagram, pass MarkerDictCH and markerLabel
sm.taylor_diagram(sdev,crmsd,ccoef, checkStats='on', styleOBS = '-', markerLabel = taylor_label,
                    colOBS = 'r', markerobs = 'o', markerLegend = 'off',stylerms ='-',colRMS='grey',
                    titleOBS = 'Observation', titleRMS = 'off', titleRMSDangle=20, colCOR='dimgrey', 
                    MarkerDictCH=marD, alpha=0.2, markerSize= 9) 

```
or with another combination of markers and labels:
```
# here, we do not pass '*' as a marker at all
marD = {'d': {'w': ['darkorange', 'darkgoldenrod'], 'k': ['cadetblue'], 'blue': ['darkgoldenrod', 'cadetblue']}, 'p': {'w': ['darkorange'], 'k': ['darkorange', 'red']}}

# here, we have three different facecolor categories
taylor_label = ['hist', 'present', 'future']

sm.taylor_diagram(sdev,crmsd,ccoef, checkStats='on', styleOBS = '-', markerLabel = taylor_label,
                    colOBS = 'r', markerobs = 'o', markerLegend = 'off',stylerms ='-',colRMS='grey',
                    titleOBS = 'Observation', titleRMS = 'off', titleRMSDangle=20, colCOR='dimgrey', 
                    MarkerDictCH=marD, alpha=0.2, markerSize= 9) 


```

Does this help?

**Comment by dabeljmu** [comment] 2021-08-24 15:28
@CarolineHaslebacher 
Hi Caroline,

thanks a lot for your quick, detailed answers and help. I figured out that the plot looks like it was planned and by the way increased my python-knowledge. A win-win-situation :)

Greetings,
Daniel

**Comment by dabeljmu** [comment] 2021-08-24 15:29
Hi Caroline,

thanks a lot for your quick, detailed answers and help. Now the plot looks like it was planned and by the way my python-knowledge has increased. A win-win-situation :)

Greetings,
Daniel

**Comment by PeterRochford** [comment] 2023-03-15 16:43
I have added a 'markers" option to the SkillMetrics package in version 1.2.2 that I hope to release soon. This allows the user to individually control of the marker label, label color, symbol, size, face color, and edge color via specifications given via a dictionary. Refer to the examples [Target 11](https://github.com/PeterRochford/SkillMetrics/wiki/Examples:-Target-Diagrams#target-diagram-example-11) and [Taylor 15](https://github.com/PeterRochford/SkillMetrics/wiki/Examples:-Taylor-Diagrams#taylor-diagram-example-15).  

I believe this should meet your needs and more. Let me know if you run into more issues.

**Comment by JiWenzheng** [comment] 2023-03-16 07:00
> I have added a 'markers" option to the SkillMetrics package in version 1.2.2 that I hope to release soon. This allows the user to individually control of the marker label, label color, symbol, size, face color, and edge color via specifications given via a dictionary. Refer to the examples [Target 11](https://github.com/PeterRochford/SkillMetrics/wiki/Examples:-Target-Diagrams#target-diagram-example-11) and [Taylor 15](https://github.com/PeterRochford/SkillMetrics/wiki/Examples:-Taylor-Diagrams#taylor-diagram-example-15).
> 
> I believe this should meet your needs and more. Let me know if you run into more issues.

Thank you very much for your work. May I ask when the 1.22 version of SkillMetrics will be released, the version I am currently using cannot run Taylor 15, because it seems that many parameters are missing in the source code.

**Comment by PeterRochford** [comment] 2023-03-19 23:11
SkillMetrics 1.2.2 is now available.

**Closed by PeterRochford** 2023-03-19 23:11 UTC

**Comment by PeterRochford** [comment] 2023-03-20 02:02
SkillMetrics 1.2.2 is now available via pip: https://pypi.org/project/SkillMetrics.
